name: "Statistical toolbox to analyze citizen science data"
title: "Statistical toolbox to analyze citizen science data"
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
theme: jekyll-theme-minimal
